// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFXN1DBJBMpjTCz4Tv8huNM3oWcYVYyeQ',
    appId: '1:621239592737:web:40db983fe8094cd06f4060',
    messagingSenderId: '621239592737',
    projectId: 'qvent-74d2c',
    authDomain: 'qvent-74d2c.firebaseapp.com',
    storageBucket: 'qvent-74d2c.appspot.com',
    measurementId: 'G-X6W6Z2MBBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAh73_45o8JAQXFP_faKK93mQcIt_OfXw',
    appId: '1:621239592737:android:7711cb3b570e88846f4060',
    messagingSenderId: '621239592737',
    projectId: 'qvent-74d2c',
    storageBucket: 'qvent-74d2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAql-9FJ-o4gOm97yyRf7Oq0N33XK0t5Kc',
    appId: '1:621239592737:ios:cc919f30f913cb486f4060',
    messagingSenderId: '621239592737',
    projectId: 'qvent-74d2c',
    storageBucket: 'qvent-74d2c.appspot.com',
    iosClientId: '621239592737-nbruhrg3tghb7o80cuidfeb6mvk8d16s.apps.googleusercontent.com',
    iosBundleId: 'com.example.qvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAql-9FJ-o4gOm97yyRf7Oq0N33XK0t5Kc',
    appId: '1:621239592737:ios:cc919f30f913cb486f4060',
    messagingSenderId: '621239592737',
    projectId: 'qvent-74d2c',
    storageBucket: 'qvent-74d2c.appspot.com',
    iosClientId: '621239592737-nbruhrg3tghb7o80cuidfeb6mvk8d16s.apps.googleusercontent.com',
    iosBundleId: 'com.example.qvent',
  );
}
